---
version: '2'
services:
  mongo1:
    build:
      context: .
      dockerfile: mongo.Dockerfile
    container_name: mongo1
    hostname: mongo1
    ports:
      - "27017:27017"
    command: --replSet rs0 --oplogSize 128
    networks:
      - spotlight
    restart: always

  mongo-setup:
    build:
      context: .
      dockerfile: mongo.Dockerfile
    container_name: mongo-setup
    depends_on:
      - mongo1
    networks:
      - spotlight
    entrypoint:
      [
        "bash",
        "-c",
        "sleep 20 && mongosh --host mongo1:27017 config-replica.js && sleep 20",
      ]
    restart: "no"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8089:8081
    networks:
      - spotlight
    depends_on:
      - mongo1
      - mongo-setup
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo1:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  spotlight:
    name: spotlight
    external: true
